"""Additional build-to-application lessons kept separate from the core generator."""

from __future__ import annotations


def register(add, md, code) -> None:
    def lesson(path, title, objectives, sections, exercises):
        cells = []
        for heading, prose, source in sections:
            cells.append(md(f"## {heading}\n\n{prose}"))
            if source:
                cells.append(code(source))
        add(path, title, objectives, cells, exercises)

    def dense(path, title, objectives, parts, snippets, exercises):
        cells = []
        for index, part in enumerate(parts, 1):
            heading, body = part
            cells.append(md(f"## {heading}\n\n{body}"))
            cells.append(code(snippets[index - 1]))
        cells.append(md("""
        ## Reference workflow and evidence standard

        Treat the notebook as an experiment, not a recipe. State the question, freeze inputs and
        success criteria, establish the simplest baseline, change one material factor, and retain raw
        outputs needed to diagnose failures. Record model, tokenizer, template, data and code revisions;
        hardware and dtype; random seeds; generation or optimization configuration; token counts;
        latency and memory; and results by meaningful slice. A demonstration that runs is evidence of
        plumbing, not evidence of general capability.

        Test boundaries as well as the happy path: empty and maximum-length inputs, malformed records,
        multilingual or code text, unavailable dependencies, cancellation, and adversarial content.
        Keep credentials in environment or Colab Secrets and never serialize them with artifacts. Pin
        remote revisions, review licenses and custom code, validate saved artifacts in a fresh process,
        and prefer deterministic validators wherever outputs can be checked mechanically.

        Before applying the technique, compare it with prompting, retrieval, a smaller model, or no
        model. Report quality together with compute, storage, latency, and operational complexity. Use
        held-out data and paired comparisons, disclose uncertainty and negative results, and define a
        rollback path. These practices connect low-level understanding to reliable application work.

        A useful completion checklist asks four separate questions. Is the mathematical contract clear
        enough to predict shapes, masks, reductions, and failure cases? Does the implementation reproduce
        a tiny hand-worked or deterministic reference? Does the measured result survive a held-out set,
        relevant slices, and an ablation against a simpler baseline? Can another person reload the exact
        artifacts and reconstruct the claim from the manifest? Passing only the first two establishes a
        tutorial demonstration; passing all four supports an engineering decision. When a result fails,
        preserve the counterexample and update the test suite before changing the implementation.

        Finally, separate correctness, capability, efficiency, and safety conclusions. A correct
        implementation may have weak capability; a capable prototype may be too costly or unsafe to
        deploy. Name the population to which each conclusion applies and avoid converting a single
        metric into a universal ranking. Track assumptions beside results, especially tokenizer and
        template compatibility, data rights, access-control boundaries, and hardware-specific behavior.
        Leave exercises with an executable acceptance criterion, a baseline result, and a short written
        interpretation. That combination turns exploratory code into cumulative course evidence that can
        be revisited when libraries, model families, or deployment engines change.
        """))
        add(path, title, objectives, cells, exercises)

    dense("00_prerequisites/01_numpy_for_llms.ipynb", "NumPy Foundations for LLM Engineering", ["Master shapes, axes, broadcasting, indexing, and dtypes", "Implement stable probability and attention operations", "Debug vectorized numerical code with explicit invariants"], [
        ("1.1 Arrays are typed strided views", "Shape names the logical axes while strides map indices to memory. LLM code repeatedly moves among batch, sequence, head, and feature axes, so most silent failures are axis errors. Reshape may share storage; transpose usually changes strides; advanced indexing generally copies. Inspect shape, dtype, strides, byte count, and memory sharing. Token IDs remain integers while activations are floating point. Broadcasting aligns from the right and can create an accidental quadratic temporary when singleton dimensions are missing. Write shape comments and assertions at every interface rather than relying on a plausible output."),
        ("1.2 Vectorization and tensor algebra", "Embedding lookup is row indexing in a vocabulary-by-width matrix. Linear projections contract a feature axis. `einsum` makes named contractions explicit and is useful for deriving batched multi-head operations, even when production kernels use specialized matrix multiplication. Reductions must specify the axis and often retain dimensions for later broadcasting. Verify a vectorized implementation against a tiny loop, then profile warmed operations. Concise expressions can still allocate large intermediates or traverse memory repeatedly; vectorization is a performance tool only when memory behavior is understood."),
        ("1.3 Stable probability computation", "Softmax must subtract the row maximum before exponentiation. Log-softmax uses log-sum-exp rather than taking a logarithm after probabilities have underflowed. Cross-entropy selects negative target log-probabilities and averages only eligible labels. Perplexity exponentiates mean token loss and is comparable only with the same tokenizer, corpus, boundaries, and masks. Floating tests use tolerances and invariants: finite nonnegative probabilities sum to one, a constant logit shift changes nothing, and ignored positions contribute neither numerator nor denominator."),
        ("1.4 Attention and scientific practice", "Scaled dot-product attention contracts queries with keys, divides by square root of head width, applies a causal or padding mask, softmaxes over key positions, and mixes values. This transparent NumPy form materializes the quadratic score matrix and is a reference rather than a long-context implementation. Use explicit random generators, separate data streams, and avoid reseeding loops. Test extreme logits, batch or sequence length one, empty selections, masked rows, and dtype changes. Record shapes and timings so later PyTorch and fused implementations can be checked against the same mathematical result."),
    ], [
        'import numpy as np\nx=np.arange(24,dtype=np.float32).reshape(2,3,4); y=x.transpose(0,2,1)\nprint(x.shape,x.strides,y.shape,y.strides,np.shares_memory(x,y))',
        'rng=np.random.default_rng(42); e=rng.normal(size=(17,8)); ids=np.array([[1,4,1],[3,2,9]])\nh=e[ids]; w=rng.normal(size=(8,12)); print(h.shape,np.einsum("btf,fd->btd",h,w).shape)',
        'def log_softmax(x):\n m=x.max(-1,keepdims=True); z=x-m; return z-np.log(np.exp(z).sum(-1,keepdims=True))\nl=np.array([[1000.,1001.,999.]]); print(np.exp(log_softmax(l)), -log_softmax(l)[0,1])',
        'def softmax(x):\n z=x-x.max(-1,keepdims=True); e=np.exp(z); return e/e.sum(-1,keepdims=True)\nrng=np.random.default_rng(7); q=rng.normal(size=(1,2,4,8)); k=rng.normal(size=q.shape); v=rng.normal(size=q.shape)\ns=np.einsum("bhtd,bhsd->bhts",q,k)/np.sqrt(8); s=np.where(np.tril(np.ones((4,4),bool))[None,None],s,-np.inf)\np=softmax(s); print(np.einsum("bhts,bhsd->bhtd",p,v).shape,p.sum(-1))'
    ], ["Implement masked cross-entropy.", "Prove a vectorized attention result matches loops.", "Diagnose three broadcasting bugs."])

    dense("00_prerequisites/02_pytorch_for_llms.ipynb", "PyTorch Tensors, Autograd, Modules, and Training", ["Use devices, dtypes, views, modules, datasets, and state dictionaries", "Derive and verify reverse-mode gradients", "Build and resume a correct training loop"], [
        ("2.1 Tensors, devices, modules, and state", "A tensor combines typed storage, shape and stride metadata, device, and optional gradient history. Move batches once at boundaries and make device/dtype choices explicit. Transposed tensors may be non-contiguous; clone copies, detach stops history, and NumPy conversion is limited to compatible CPU tensors. `nn.Module` recursively registers child modules and Parameters so device movement, optimization, modes, and serialization work. Persistent non-trainable tensors belong in buffers. Inspect named parameters, buffers, unique storage, trainable counts, and optimizer groups before trusting a run."),
        ("2.2 Reverse-mode automatic differentiation", "Autograd records differentiable operations involving tensors that require gradients and propagates vector-Jacobian products backward. It is efficient when one scalar loss depends on many parameters. Gradients accumulate into leaf `.grad`, so reset them at optimizer-update boundaries. In-place operations can invalidate saved intermediates; `.data` bypasses safety checks. Verify custom operations with central finite differences or gradcheck in float64. A missing gradient often indicates detach, NumPy conversion, no-grad construction, an unused parameter, or optimizer exclusion—not a need for arbitrary `retain_graph=True`."),
        ("2.3 Data and optimization contracts", "Dataset maps indices to records, sampler chooses order, DataLoader fetches, and collator constructs padded or packed batches. Inspect actual decoded batches and label masks. Reduction defines weighting: averaging unequal batch means is not token-weighted loss. The update sequence is forward, correctly reduced loss, backward, optional unscale, gradient clipping, optimizer step, scheduler step, and zeroing. `train()` and `eval()` affect dropout-like modules but do not control gradient recording; use inference mode for evaluation and restore the prior mode."),
        ("2.4 Precision, checkpointing, and debugging", "FP16 has narrow exponent range, BF16 retains wider range, and autocast selects eligible operations; mixed precision still needs numerical regression tests. Unscale before clipping and log skipped updates. A training checkpoint contains model, optimizer, scheduler, scaler, RNG, step, sampler/data position, and configuration, whereas a deployment artifact may contain only weights and inference metadata. Test a continuous run against a save/resume branch. First overfit one batch and assert finite gradients and changing parameters, then add acceleration, accumulation, checkpointing, compilation, or distribution one axis at a time."),
    ], [
        'import torch\nx=torch.arange(24,dtype=torch.float32).reshape(2,3,4); y=x.transpose(1,2)\nprint(x.stride(),y.stride(),y.is_contiguous(),y.contiguous().view(2,-1).shape)',
        'w=torch.tensor([2.,-1.],requires_grad=True); x=torch.tensor([3.,4.]); loss=((w*x).sum()-5).square(); loss.backward()\nprint(loss.item(),w.grad)',
        'from torch import nn\nmodel=nn.Sequential(nn.Linear(4,16),nn.GELU(),nn.Linear(16,3)); opt=torch.optim.AdamW(model.parameters(),lr=1e-3)\na=torch.randn(8,4); target=torch.randint(0,3,(8,)); opt.zero_grad(set_to_none=True); loss=nn.functional.cross_entropy(model(a),target); loss.backward(); print(nn.utils.clip_grad_norm_(model.parameters(),1.0)); opt.step()',
        'from pathlib import Path\np=Path("artifacts/prerequisites/model.pt"); p.parent.mkdir(parents=True,exist_ok=True); torch.save({"model":model.state_dict(),"optimizer":opt.state_dict(),"rng":torch.get_rng_state()},p)\nrestored=type(model)(*list(model.children())); restored.load_state_dict(torch.load(p,map_location="cpu",weights_only=True)["model"]); print("reloaded")'
    ], ["Check an analytic gradient with finite differences.", "Implement token-weighted accumulation.", "Prove checkpoint resume matches continuous training."])

    dense("00_prerequisites/03_prerequisite_integration.ipynb", "Prerequisite Integration: From Arrays to a Trainable Token Model", ["Translate NumPy reference mathematics into PyTorch", "Validate gradients, batches, masking, and checkpoints", "Use a disciplined debugging ladder before larger LLM experiments"], [
        ("3.1 Trace one contract across libraries", "The safest bridge from numerical foundations to language-model code is a shape-first reference. Begin with integer token IDs shaped batch by time, gather embedding rows, project hidden features to vocabulary logits, shift predictions against next-token labels, and reduce only valid token losses. Implement the same small computation in NumPy and PyTorch with copied weights. Matching forward values isolates framework mechanics from model design. Write every axis, dtype, and valid range beside the interface; many apparent optimization failures are actually transposes, off-by-one shifts, or unintended broadcasting."),
        ("3.2 Verify derivatives independently", "Autograd is reliable when the computation supplied to it is correct. Select a tiny parameter tensor, compute central finite differences with several step sizes, and compare them with reverse-mode gradients in float64. Large disagreement can reveal a detached tensor, an in-place mutation, a nondifferentiable operation, or a faulty reduction. Gradient checks are expensive and belong on tiny deterministic examples. Afterward, inspect per-parameter gradient existence, finiteness, scale, and update magnitude during training rather than relying only on a declining scalar loss."),
        ("3.3 Build the smallest honest data path", "A language-model batch needs tokens, attention or validity information, and labels whose ignored positions are explicit. The collator owns padding and batch construction; the objective owns causal shifting and token-weighted reduction. Inspect decoded rows after every transformation. Overfit one tiny batch with dropout disabled and confirm that the target-token loss approaches zero. Then evaluate under inference mode without recording gradients. This test jointly exercises data, model, objective, optimizer, and mode switching while remaining small enough to diagnose exactly."),
        ("3.4 Reproducibility and the debugging ladder", "Fix independent random generators, record configuration and package versions, and save model, optimizer, step, and RNG state. Compare an uninterrupted run with a save-and-resume branch on identical batches. Debug in layers: establish shapes and dtypes, compare a hand reference, overfit one batch, test checkpoint equivalence, then introduce realistic data and only afterward mixed precision or acceleration. Each new feature should have a measured reason and a regression test. This ladder is reused throughout pretraining, fine-tuning, retrieval training, evaluation, and production serving."),
    ], [
        'import numpy as np, torch\nrng=np.random.default_rng(3); ids=np.array([[0,2,1],[3,1,4]]); emb=rng.normal(size=(5,4)); proj=rng.normal(size=(4,5))\nnp_logits=emb[ids]@proj; pt_logits=torch.tensor(emb)[torch.tensor(ids)]@torch.tensor(proj); print(np.max(np.abs(np_logits-pt_logits.numpy())),np_logits.shape)',
        'w=torch.tensor([.4,-.7],dtype=torch.float64,requires_grad=True); f=lambda z:(z.sin()*z.square()).sum(); f(w).backward(); eps=1e-6\nfd=[]\nfor i in range(w.numel()):\n p=w.detach().clone(); m=w.detach().clone(); p[i]+=eps; m[i]-=eps; fd.append(((f(p)-f(m))/(2*eps)).item())\nprint(w.grad.tolist(),fd)',
        'from torch import nn\ntokens=torch.tensor([[1,2,3,4],[2,3,0,0]]); labels=tokens[:,1:].clone(); labels[1,1:]=-100\nmodel=nn.Sequential(nn.Embedding(5,8),nn.Linear(8,5)); logits=model(tokens[:,:-1]); loss=nn.functional.cross_entropy(logits.reshape(-1,5),labels.reshape(-1),ignore_index=-100,reduction="sum")/(labels!=-100).sum(); print(logits.shape,loss.item())',
        'torch.manual_seed(7); state={"model":model.state_dict(),"rng":torch.get_rng_state(),"step":0}; clone=nn.Sequential(nn.Embedding(5,8),nn.Linear(8,5)); clone.load_state_dict(state["model"]); print(all(torch.equal(a,b) for a,b in zip(model.state_dict().values(),clone.state_dict().values())))'
    ], ["Make the NumPy and PyTorch masked losses agree.", "Overfit a four-sequence corpus and explain every tensor shape.", "Prove a resumed two-step run matches an uninterrupted run."])

    dense("01_math_foundations/06_train_a_tokenizer.ipynb", "Training and Evaluating a Tokenizer", ["Train a byte-level BPE tokenizer", "Design special tokens and normalization", "Measure fertility, coverage, boundaries, and artifact compatibility"], [
        ("6.1 Tokenization is learned infrastructure", "A tokenizer fixes the model vocabulary and sequence representation. Byte-level BPE begins from bytes so every string is representable, then merges frequent adjacent symbols to improve compression. WordPiece and Unigram use different vocabulary objectives; SentencePiece can learn directly from raw text. Corpus language, code, identifiers, normalization, and sampling determine which strings are efficient. Split evaluation before fitting and record provenance. Vocabulary size trades shorter sequences against larger embedding/output matrices and sparse rare-token learning."),
        ("6.2 Normalization, pre-tokenization, and specials", "Unicode normalization, case folding, whitespace, and pre-tokenization can irreversibly change text. A causal model needs deliberate BOS, EOS, PAD, unknown, chat-role, tool, and multimodal tokens. Special strings must be indivisible and their IDs stable. Reusing EOS as PAD can be safe only when attention and label masks distinguish genuine EOS. Adding vocabulary after model pretraining creates new random embedding and output rows; changing segmentation invalidates learned correspondence even when old token strings remain."),
        ("6.3 Train, inspect, and package", "Hugging Face Tokenizers separates model, normalizer, pre-tokenizer, trainer, decoder, and post-processor. Freeze code and library versions, shuffle deterministically, and avoid evaluation text. Inspect learned merges and encode/decode examples rather than trusting vocabulary size. Package tokenizer JSON, special-token map, configuration, template, training-data fingerprint, and license. Test reload in a fresh process and exact round trips for bytes, Unicode, whitespace, control characters, code, and multiple languages."),
        ("6.4 Evaluate before pairing with a model", "Fertility measures tokens per word or character; report length distributions by language/domain rather than one mean. Count unknowns where applicable, byte fallback frequency, fragmented identifiers, special-token collisions, and maximum-context truncation. Compression alone is not quality: tokens should support learnable recurring units without obscuring boundaries. Compare vocabularies under fixed corpus and downstream compute. A new tokenizer belongs with a newly initialized or deliberately adapted model; do not casually replace the tokenizer of a pretrained checkpoint."),
    ], [
        'corpus=["attention predicts tokens","tokenizers compress recurring pieces","byte fallback preserves text"]*20\nprint(len(corpus),len(set(corpus)))',
        'try:\n from tokenizers import Tokenizer,models,pre_tokenizers,decoders,trainers\n tok=Tokenizer(models.BPE(unk_token="<unk>")); tok.pre_tokenizer=pre_tokenizers.ByteLevel(); tok.decoder=decoders.ByteLevel(); tok.train_from_iterator(corpus,trainers.BpeTrainer(vocab_size=120,special_tokens=["<pad>","<bos>","<eos>","<unk>"])); print(tok.encode("attention tokens").tokens)\nexcept ImportError: print("Colab setup installs tokenizers through Transformers")',
        'tests=[" leading space","naïve café","中文","👩🏽‍💻","x_y::HTTP42"]\nif "tok" in globals():\n for text in tests: print(repr(text),tok.encode(text).tokens,tok.decode(tok.encode(text).ids)==text)',
        'if "tok" in globals():\n for text in tests: print(repr(text),len(tok.encode(text).ids),"tokens",len(text),"characters")'
    ], ["Train two vocabulary sizes and compare fertility.", "Add a chat-token policy and collision tests.", "Explain why swapping a pretrained tokenizer breaks the model."])

    dense("01_math_foundations/11_scaling_laws_compute_planning.ipynb", "Scaling Laws and Training-Compute Planning", ["Estimate parameter, token, memory, and FLOP budgets", "Fit cautious empirical scaling curves", "Design pilot runs and stopping decisions"], [
        ("11.1 What scales", "Model size, active parameters, training tokens, sequence length, batch tokens, optimizer updates, numerical precision, and hardware utilization are different quantities. Dense decoder training FLOPs are often estimated with a constant times parameters times tokens, but embeddings, attention, MoE routing, rematerialization, and inefficient kernels change the constant. Report assumptions and measured throughput. Epochs are misleading across corpora; tokens and compute make experiments comparable. Storage also includes raw/tokenized data, optimizer state, checkpoints, logs, and evaluation artifacts."),
        ("11.2 Empirical power laws", "Loss frequently follows approximate power laws over useful scale ranges, with an irreducible floor. Fit in log space only after plotting residuals and separating architecture or data-regime changes. A smooth aggregate curve can hide language, domain, memorization, safety, or downstream regressions. Extrapolation beyond observed compute has wide structural uncertainty. Scaling laws help allocate pilots and detect underperforming runs; they do not replace evaluation or guarantee emergent behavior."),
        ("11.3 Compute-optimal tradeoffs", "Given fixed compute, increasing parameters leaves fewer tokens and increasing tokens leaves a smaller model. Compute-optimal guidance depends on data quality, reuse, inference demand, and target capabilities. A smaller model trained longer can be preferable when serving dominates lifetime cost; a larger undertrained model may adapt differently. Deduplicated unique tokens, repeated tokens, synthetic mixtures, and curriculum order are not interchangeable. Treat token-to-parameter ratios as hypotheses to test with pilots, not universal constants."),
        ("11.4 Planning and monitoring", "Run small matched pilots varying one scale axis, fit curves with uncertainty, and reserve budget for failures, evaluation, checkpointing, and ablations. Estimate memory for weights, gradients, optimizer states, activations, KV/cache workspaces, and fragmentation. During training compare observed loss with predicted bands, tokens per second, utilization, gradient norms, and data health. Stop or intervene on evidence, not sunk cost. Archive failed runs and document carbon, financial, and opportunity costs alongside quality."),
    ], [
        'def dense_flops(params,tokens,multiplier=6): return multiplier*params*tokens\nfor p,t in [(1e8,2e9),(1e9,2e10),(7e9,1.4e11)]: print(p,t,dense_flops(p,t))',
        'import numpy as np\ncompute=np.array([1,2,4,8,16.]); loss=2.1+.8*compute**-.3\ncoef=np.polyfit(np.log(compute),np.log(loss-2.1),1); print("exponent",coef[0])',
        'budget=6e20\nfor params in [1e8,5e8,1e9,3e9]: print(params,"tokens",budget/(6*params))',
        'def gib(params,weight=2,grad=2,optimizer=8): return params*(weight+grad+optimizer)/2**30\nfor p in [1e8,1e9,7e9]: print(p,gib(p))'
    ], ["Fit a power law and bootstrap its exponent.", "Plan three matched pilot runs.", "Compare training and lifetime inference compute."])

    dense("01_math_foundations/12_interpretability_debugging.ipynb", "Interpretability and Model Debugging", ["Inspect activations, attention, logits, and gradients with hooks", "Use probes and interventions without overstating causality", "Connect mechanistic evidence to behavioral evaluation"], [
        ("12.1 Observation versus explanation", "Hidden states, attention weights, gradients, and token probabilities are measurements of a particular forward pass. Attention weight is not automatically feature importance or causal explanation. A linear probe shows information is decodable, not that the model uses it. Begin with a behavioral phenomenon and falsifiable hypothesis, choose controls, and preserve exact prompt/tokenizer/model revisions. Aggregate plots can erase token-, head-, layer-, or example-specific behavior."),
        ("12.2 Hooks and logit lens", "PyTorch forward hooks capture module inputs or outputs; remove them after use and avoid mutation. Requesting hidden states or attentions increases memory and can change optimized kernels. A logit lens applies the final normalization and unembedding to intermediate residual states to inspect evolving token evidence, but intermediate representations were not necessarily trained to be directly decoded. Compare with tuned lenses or interventions and include random or shuffled controls."),
        ("12.3 Probes, attribution, and patching", "Probes range from linear classifiers to expressive models; high-capacity probes can learn the task rather than reveal representation. Use train/validation splits, balanced baselines, selectivity controls, and layer sweeps. Gradient attribution is local and sensitive to saturation or baselines. Activation patching replaces a component between clean and corrupted runs and measures causal restoration, but intervention location, metric, and distribution matter. Multiple components may be redundant."),
        ("12.4 Features and responsible claims", "Neuron inspection often finds polysemantic units. Sparse autoencoders attempt to decompose activations into sparse learned features but depend on dataset, layer, width, sparsity, and interpretation method. Automated labels need human and causal validation. Interpretability can debug tokenization, masks, template boundaries, memorization, and regressions; it is not a safety certificate. Release claims with methods, prompts, controls, uncertainty, counterexamples, and code sufficient to reproduce the intervention."),
    ], [
        'import torch\nfrom torch import nn\nmodel=nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,3)); captured={}\nh=model[0].register_forward_hook(lambda m,i,o: captured.update(hidden=o.detach())); out=model(torch.randn(2,4)); h.remove(); print(out.shape,captured["hidden"].shape)',
        'hidden=torch.randn(2,5,8); unembed=torch.randn(8,11); probs=(hidden@unembed).softmax(-1); print(probs.shape,probs.argmax(-1))',
        'clean=torch.tensor([1.,2.,3.]); corrupt=torch.tensor([1.,-2.,3.]); patched=corrupt.clone(); patched[1]=clean[1]\nmetric=lambda x:x.sum(); print(metric(clean),metric(corrupt),metric(patched))',
        'labels=torch.tensor([0,0,1,1]); feature=torch.tensor([-.9,-.7,.8,.6]); print("threshold probe",((feature>0).long()==labels).float().mean().item())'
    ], ["Capture and remove hooks safely.", "Design an activation-patching control.", "Critique an attention-as-explanation claim."])

    dense("02_training/23_knowledge_reasoning_distillation.ipynb", "Knowledge and Reasoning Distillation", ["Compare sequence, logit, and on-policy distillation", "Build teacher-data and KL objectives", "Measure transferred capability, error, and serving benefit"], [
        ("23.1 What is transferred", "Sequence distillation trains a student on teacher-generated targets; logit distillation matches softened teacher distributions; intermediate-feature methods align representations; on-policy distillation scores student-generated trajectories. Distillation can compress a model, transfer instruction behavior, or teach reasoning and tools. It cannot exceed evidence available from tasks, teachers, environments, and verifiers without additional exploration. Teacher outputs contain correlated factual, stylistic, safety, and calibration errors."),
        ("23.2 Temperature and objectives", "KL divergence between teacher and student distributions exposes dark knowledge in non-argmax probabilities. Temperature softens distributions; conventional objectives rescale by temperature squared so gradient magnitude remains comparable. Tokenizer mismatch complicates token-level alignment, making sequence targets or character/span alignment safer. Combine distillation with ground-truth loss deliberately and mask prompt/padding positions. Direction of KL changes mode-covering behavior."),
        ("23.3 Reasoning and tool traces", "Reasoning distillation uses worked solutions, rejection-sampled correct traces, or teacher trajectories. Verify final outcomes independently and filter invalid intermediate steps where possible. Long polished rationales are not necessarily faithful. For tools, retain schemas, calls, results, recovery examples, and permission denials; never train authorization from model text. On-policy sampling reduces train-test mismatch but costs inference and requires stable teachers or rewards."),
        ("23.4 Evaluation and economics", "Compare student with untrained student, teacher, and simpler SFT baselines under fixed prompts. Evaluate target capability, general retention, calibration, safety, pass@k, tool behavior, and teacher-error reproduction. Measure total generation/training cost against lifetime serving savings, artifact size, memory, latency, and throughput. A smaller student may need more tokens to solve reasoning tasks. Preserve teacher revisions, generation settings, filters, data lineage, objective weights, and licenses."),
    ], [
        'import torch\nt=torch.tensor([[3.,1.,0.]]); s=torch.tensor([[1.,1.,1.]],requires_grad=True)\nT=2.; loss=torch.nn.functional.kl_div(torch.log_softmax(s/T,-1),torch.softmax(t/T,-1),reduction="batchmean")*T*T; loss.backward(); print(loss.item(),s.grad)',
        'records=[{"prompt":"2+2","teacher":"FINAL: 4","verified":True},{"prompt":"3*7","teacher":"FINAL: 20","verified":False}]\nprint([r for r in records if r["verified"]])',
        'teacher_tokens=10_000_000; student_training=2_000_000; saving_per_request=800; requests=20_000\nprint("net token-equivalent",requests*saving_per_request-teacher_tokens-student_training)',
        'metrics={"teacher_accuracy":.91,"student_before":.62,"student_after":.84,"latency_ratio":.35}; print(metrics)'
    ], ["Implement temperature sweeps.", "Verify and filter reasoning traces.", "Calculate distillation break-even for a workload."])

    dense("03_huggingface/25_prompting_context_chat_templates.ipynb", "Prompting, Context Engineering, and Chat Templates", ["Design prompts as versioned probabilistic interfaces", "Render and test Hugging Face chat templates", "Evaluate few-shot examples, context budgets, and injection boundaries"], [
        ("25.1 Prompting is interface design", "A prompt conditions a trained distribution; it does not install a rule or permission boundary. State the task, audience, supplied data, constraints, uncertainty behavior, and output contract. Use delimiters to distinguish instructions from untrusted data, but assume the model may still follow injected text. Positive instructions often work better than lists of prohibitions. Establish a zero-shot baseline before decomposition or few-shot examples, and measure success on frozen cases rather than optimizing one anecdote."),
        ("25.2 Few-shot and context engineering", "Examples teach local patterns without changing weights, but selection, order, label balance, similarity, and length affect behavior. Keep examples free of evaluation leakage and retrieve them by task-relevant similarity only under authorization. Context engineering chooses all messages, evidence, tool schemas, memory, and prior results under a token budget. Preserve authoritative constraints and unresolved commitments; summarize low-priority history with provenance. More context can distract, increase latency, and expose injection."),
        ("25.3 Chat templates are model artifacts", "Instruct checkpoints are trained on exact control tokens and role serialization. `apply_chat_template(tokenize=True)` is safest because rendering then ordinary tokenization can duplicate special tokens. Understand `add_generation_prompt` and continuing a final message, EOS boundaries, assistant masks, tool arguments, and reasoning controls. Templates are Jinja stored with tokenizer artifacts; whitespace changes can matter. Multimodal templates belong to processors and emit media placeholders. Pin, inspect, and regression-test rendered IDs across training and every serving engine."),
        ("25.4 Prompt evaluation and escalation", "Version prompt source, variables, rendered text hash, template/model/tokenizer revisions, and decoding. Evaluate correctness, constraint adherence, schema validity, abstention, robustness to irrelevant changes, injection, token cost, and latency. Use paired comparisons and slice results. When prompt complexity grows, decide whether constrained decoding, retrieval, tools, SFT, or deterministic code owns the requirement. Prompts cannot guarantee authorization, factuality, confidentiality, or exact computation; application controls remain authoritative."),
    ], [
        'cases=[{"input":"refund policy","expected_fields":{"answer","sources"}},{"input":"unknown policy","must_abstain":True}]\nprint(cases)',
        'examples=[("positive","Return one JSON object with answer and sources."),("negative","Do not ramble or omit JSON or add markdown.")]\nprint(*examples,sep="\\n")',
        'try:\n from transformers import AutoTokenizer\n tok=AutoTokenizer.from_pretrained("Qwen/Qwen2.5-0.5B-Instruct",local_files_only=True); messages=[{"role":"user","content":"Define perplexity."}]; ids=tok.apply_chat_template(messages,tokenize=True,add_generation_prompt=True); print(tok.decode(ids),len(ids))\nexcept Exception as e: print("Load/cache the public tokenizer to inspect its exact template:",type(e).__name__)',
        'results=[{"prompt":"v1","valid":8,"correct":6,"tokens":900},{"prompt":"v2","valid":10,"correct":7,"tokens":1300}]\nfor r in results: print(r["prompt"],"accuracy",r["correct"]/10,"tokens/correct",r["tokens"]/r["correct"])'
    ], ["Compare zero-shot and few-shot prompts on a frozen set.", "Write and test a minimal Jinja chat template.", "Build a token-budgeted context assembler."])

    dense("03_huggingface/26_hf_inference_model_selection.ipynb", "Hugging Face Inference APIs and Open-Model Selection", ["Move from pipeline to forward passes and hosted endpoints", "Select models using measured compatibility and constraints", "Control device maps, dtypes, batching, trust, and revisions"], [
        ("26.1 Select an artifact, not a leaderboard row", "Define task, languages, modalities, latency, throughput, memory, context, license, privacy, tool/structure needs, and hardware before choosing a model. Distinguish base, instruct, reasoning, dense, and MoE variants; total and active parameters differ. Inspect model and dataset cards, configuration, tokenizer, chat template, architecture support, quantized derivatives, and immutable revisions. Leaderboards suggest candidates but may use different prompts, templates, contamination, and hardware. Run a task-specific baseline and record exclusions."),
        ("26.2 Abstraction ladder", "`pipeline` provides task preprocessing and postprocessing for fast baselines. Auto tokenizer/processor plus AutoModel exposes batching and generation. Direct forward passes expose logits, loss, hidden states, and cache behavior. `InferenceClient` targets remote providers; dedicated endpoints and local servers change operational ownership. Choose the highest abstraction that exposes required controls, then inspect what it adds. Do not mix pipeline-returned full text with newly generated tokens or assume model-specific output schemas are uniform."),
        ("26.3 Loading and memory", "Pin model and tokenizer commits together. Review `trust_remote_code` and custom repositories before execution. Choose dtype supported by hardware, use device maps deliberately, and understand offload latency. `low_cpu_mem_usage`, Safetensors, sharded checkpoints, quantization, and attention implementations affect load and residency. Set pad token and padding side based on task. Measure peak memory after warmup, not just weight size; KV cache and workspaces grow with live tokens."),
        ("26.4 Compatibility and deployment", "Test chat rendering, greedy and sampled generation, stopping, streaming, structured output, tools, logprobs, batching, cancellation, and error behavior on the exact backend. A model loading in Transformers does not guarantee optimized vLLM or SGLang support. Keep a narrow internal request contract and engine conformance tests. Compare local inference, Hugging Face providers, managed endpoints, Ollama, and vLLM by data boundary, cold start, concurrency, cost, and operations. Store raw predictions and release a model-selection decision record."),
    ], [
        'requirements={"license":"commercial-compatible","memory_gib":16,"tools":True,"min_context":8192}; candidates=[{"id":"a","memory_gib":8,"tools":True,"context":32768},{"id":"b","memory_gib":20,"tools":True,"context":65536}]\nprint([c for c in candidates if c["memory_gib"]<=requirements["memory_gib"] and c["tools"] and c["context"]>=requirements["min_context"]])',
        'try:\n from transformers import pipeline\n print("pipeline is the baseline API; guarded to avoid an implicit model download")\nexcept ImportError: print("run setup")',
        'import torch\nfor dtype in [torch.float32,torch.float16,torch.bfloat16]: print(dtype,torch.finfo(dtype).bits)',
        'contract={"chat":True,"stream":True,"tools":True,"json_schema":True,"cancel":True}; observed={"chat":True,"stream":True,"tools":False,"json_schema":True,"cancel":False}\nprint("gaps",[k for k,v in contract.items() if v and not observed.get(k)])'
    ], ["Build a model-selection scorecard.", "Compare pipeline and direct generate outputs.", "Write a backend conformance suite."])

    dense("04_retrieval/29_embedding_reranker_training.ipynb", "Training Embedding Models and Rerankers", ["Derive contrastive bi-encoder and cross-encoder objectives", "Mine hard negatives without poisoning labels", "Fine-tune and evaluate retrieval by slice"], [
        ("29.1 Representation objectives", "Bi-encoders embed query and document independently for scalable retrieval. Contrastive training raises positive similarity relative to negatives; multiple-negatives ranking uses other positives in the batch as negatives and is efficient only when false negatives are controlled. Triplet and margin losses encode relative constraints. Normalize vectors when cosine similarity is intended. Dataset pairs define relevance and can teach shortcuts from source, length, or formatting."),
        ("29.2 Negatives and mining", "Random negatives are often too easy; lexical or dense mining finds confusable candidates that teach decision boundaries. A highly ranked unlabeled document may actually be relevant, creating false-negative gradients. Use human judgments, cross-encoder filtering, known-positive sets, and iterative audits. Mine with a frozen prior model and keep evaluation documents isolated. Balance domains and query frequencies by effective pairs or tokens."),
        ("29.3 Cross-encoder rerankers", "A cross-encoder jointly reads query and candidate and predicts relevance, capturing token interactions at greater latency. Train with pointwise classification, pairwise preference, or listwise ranking objectives. Calibrate scores only for the deployment candidate distribution. Reranker training cannot recover documents absent from first-stage candidates, so freeze candidate pools when evaluating reranker improvements and measure end-to-end recall separately."),
        ("29.4 Training and evaluation", "Sentence Transformers provides losses, trainers, evaluators, and Hub-compatible artifacts. Begin with a small domain dataset and guarded run; record base revision, pooling, maximum length, prompts, batch composition, negatives, and precision. Evaluate Recall@k, MRR, nDCG, MAP, latency, index size, multilingual/domain slices, and robustness to identifiers. Compare base and tuned models on a frozen corpus, rebuild the index after any embedding change, and retain rollback lineage."),
    ], [
        'import torch\nq=torch.nn.functional.normalize(torch.randn(4,8),dim=-1); d=torch.nn.functional.normalize(torch.randn(4,8),dim=-1); logits=q@d.T/.07; labels=torch.arange(4); print(torch.nn.functional.cross_entropy(logits,labels))',
        'pool=[{"id":"d1","score":.91,"known_positive":True},{"id":"d2","score":.89,"known_positive":False},{"id":"d3","score":.2,"known_positive":False}]\nprint("audit hard negatives",[x for x in pool if not x["known_positive"] and x["score"]>.5])',
        'pointwise=torch.tensor([2.,-1.]); labels=torch.tensor([1.,0.]); print(torch.nn.functional.binary_cross_entropy_with_logits(pointwise,labels))',
        'ranking=["d3","d1","d7"]; relevant={"d1","d2"}; print("recall@3",len(set(ranking)&relevant)/len(relevant),"RR",1/2)'
    ], ["Mine and audit hard negatives.", "Compare contrastive temperatures.", "Fine-tune a small embedding model and rebuild its index."])

    dense("06_evaluation_security/40_lighteval_benchmarking.ipynb", "Reproducible LLM Benchmarking with LightEval", ["Distinguish likelihood, generation, and judge tasks", "Define reproducible benchmark configurations", "Interpret aggregate scores, contamination, and uncertainty"], [
        ("40.1 A harness standardizes mechanics", "A benchmark harness makes prompts, few-shot selection, batching, metrics, model adapters, and result serialization repeatable. It does not make a benchmark representative or uncontaminated. LightEval is the actively maintained Hugging Face-aligned option for LLM evaluation. Pin its version, task revision, model/tokenizer/template, generation configuration, and backend. Run a small smoke subset before expensive evaluation and preserve per-example outputs."),
        ("40.2 Task types", "Log-likelihood tasks compare candidate continuation probabilities and require correct token boundaries and normalization. Generative tasks decode an answer and apply exact, normalized, executable, semantic, or judge graders. Few-shot examples alter context and must be fixed by seed and selection policy. Chat templates can change results materially. Stop sequences, maximum tokens, sampling, and answer extraction are part of the benchmark definition, not incidental CLI flags."),
        ("40.3 Statistics and contamination", "Aggregate accuracy conceals slices and item dependence. Report counts, paired differences, bootstrap intervals where appropriate, and failures. Pass@k depends on number and sampling distribution. Benchmark data may appear in pretraining or synthetic instruction corpora; use contamination checks, private or newly created tests, temporal splits, and perturbations. Leaderboard comparisons are invalid when prompts, few-shot counts, revisions, or inference settings differ."),
        ("40.4 Operational workflow", "Create a manifest, inspect rendered prompts, run deterministic baselines, execute the candidate and parent under identical settings, validate completion and error counts, then publish raw predictions plus summary. Distributed evaluation must avoid duplicate items and aggregate numerators/denominators correctly. Quality changes after quantization or serving-engine migration require the same frozen suite. Standard benchmarks complement product-specific tasks, safety tests, RAG and agent trajectories; none replaces them."),
    ], [
        'config={"harness":"lighteval@pinned","tasks":["task@revision"],"fewshot":0,"seed":42,"model":"org/model@commit","template":"tokenizer@commit"}; print(config)',
        'items=[{"type":"likelihood","scores":[-.2,-1.4],"gold":0},{"type":"generation","output":"42","reference":"42"}]; print(items)',
        'import random\ndiffs=[1,0,-1,1,1,0]; rng=random.Random(42); means=[sum(rng.choices(diffs,k=len(diffs)))/len(diffs) for _ in range(1000)]; print(sorted(means)[25],sorted(means)[975])',
        'results={"completed":98,"errors":2,"expected":100}; assert results["completed"]+results["errors"]==results["expected"]; print(results)'
    ], ["Define a custom task.", "Compare two checkpoints with paired intervals.", "Audit template and contamination sensitivity."])

    dense("09_capstones/49_capstone_build_language_model.ipynb", "Capstone I: Build, Pretrain, and Instruction-Tune a Language Model", ["Integrate tokenizer, decoder, pretraining, SFT, evaluation, and artifacts", "Use explicit gates between stages", "Produce a reproducible model card and release bundle"], [
        ("49.1 Product and experiment contract", "Define a deliberately narrow model: target corpus, supported language/domain, context length, vocabulary, parameter and token budget, hardware, success metrics, and excluded uses. Establish byte or n-gram baselines and a held-out split before training. This capstone reuses implementations from prerequisites through SFT rather than hiding them in one trainer. One-epoch course runs demonstrate integration, not a useful general assistant. Create a run directory containing immutable configuration and hashes, never credentials."),
        ("49.2 Tokenizer and pretraining gate", "Train a tokenizer only on training text, test round trips and fertility, then initialize a compatible decoder from configuration. Verify causal shift, masks, parameter tying, one-batch overfit, finite gradients, and checkpoint resume. Train under a fixed token budget and evaluate held-out loss/perplexity plus generation probes. Do not advance merely because loss fell: require artifact reload, no split leakage, acceptable tokenizer behavior, and documented data lineage."),
        ("49.3 Instruction tuning gate", "Construct a small, licensed instruction dataset with exact chat template and assistant-only loss mask. Evaluate the base checkpoint first. Apply full or LoRA SFT, recording trainable parameters, effective tokens, schedule, and checkpoints. Compare base and tuned models on instruction following, output format, retention, and safety cases. A toy pretrained model may lack capacity and knowledge; negative results are expected and should be explained rather than hidden."),
        ("49.4 Release and reflection", "Package weights, configuration, tokenizer, template, generation defaults, provenance, evaluation report, and model card. Reload in a clean process and compare fixed logits. Document intended use, limitations, license, compute, data, failures, and why the model is not production-ready. The final report traces every measured behavior to a build decision and proposes the highest-value next experiment under a fixed budget."),
    ], [
        'plan={"context":128,"vocab":512,"parameters":500_000,"train_tokens":100_000,"epochs":1}; print(plan)',
        'gates={"roundtrip":True,"no_leakage":True,"one_batch_overfit":True,"checkpoint_reload":True}; print("pretrain ready",all(gates.values()))',
        'comparison={"base_format":.1,"sft_format":.8,"base_loss":4.2,"sft_retention_loss":4.5}; print(comparison)',
        'release=["config","weights","tokenizer","chat_template","model_card","eval_report","manifest"]; print(release)'
    ], ["Complete the capstone with one epoch.", "Write a model card with negative results.", "Propose a compute-matched next experiment."])

    dense("09_capstones/50_capstone_grounded_assistant.ipynb", "Capstone II: Build and Evaluate a Grounded Assistant", ["Integrate model selection, prompting, hybrid RAG, tools, and structure", "Evaluate retrieval, answers, citations, security, and latency", "Serve the system locally with a reproducible contract"], [
        ("50.1 Requirements and baseline", "Define users, questions, authoritative sources, freshness, citation and abstention rules, latency, privacy, and threat boundaries. Select an open instruct model using measured constraints and pin its tokenizer/template. Build a no-retrieval prompt baseline on a frozen dataset containing answerable, unanswerable, identifier-heavy, conflicting, stale, and adversarial cases. This reveals what retrieval must improve and prevents complexity from receiving credit for model knowledge."),
        ("50.2 Retrieval and grounded generation", "Parse versioned documents, preserve metadata and access controls, chunk with source offsets, and build lexical plus dense indexes. Evaluate each retriever, reciprocal-rank fusion, reranking, and context diversity before generation. Assemble evidence under a token budget and treat it as untrusted data. Require source IDs and abstention. Validate that citations exist and support material claims; citation presence alone is not correctness."),
        ("50.3 Tools, security, and operations", "Add one narrow read-only tool only when retrieval cannot answer current or exact information. Validate arguments and keep authorization in the host. Test indirect prompt injection, unauthorized sources, oversized documents, stale caches, tool timeouts, and malformed structured output. Trace retrieval, reranking, generation, validation, and tools with redaction. Serve through Ollama or a compatible endpoint and test the exact template and API contract."),
        ("50.4 Evaluation and release", "Compare baseline, dense, hybrid, reranked, and tool-enabled variants. Report Recall@k, MRR, answer correctness, faithfulness, citation precision/recall, abstention, latency percentiles, tokens, and critical security failures by slice. Promote only if target gains justify complexity and no authorization violation occurs. Package index/data/model/prompt revisions, deployment config, system card, rollback plan, and deletion lineage."),
    ], [
        'requirements={"citations":True,"abstain":True,"p95_seconds":3,"private_sources":True}; print(requirements)',
        'variants=["prompt_only","dense","hybrid","hybrid_reranked","hybrid_plus_tool"]; print(variants)',
        'tests=["unanswerable","conflicting_sources","injection","unauthorized_document","tool_timeout","stale_cache"]; print(tests)',
        'metrics={"recall@5":.9,"answer_accuracy":.78,"citation_precision":.94,"critical_violations":0,"p95":2.4}; print("release",metrics["critical_violations"]==0 and metrics["p95"]<=3)'
    ], ["Build all five ablation variants.", "Validate claim-level citations.", "Produce a system card and rollback drill."])

    dense("09_capstones/51_capstone_operate_agent_system.ipynb", "Capstone III: Operate a Durable Multi-Agent System", ["Combine durable state, MCP tools, approvals, and specialist agents", "Evaluate trajectories, failure recovery, security, and capacity", "Produce an operational release with rollback and governance"], [
        ("51.1 Workflow architecture", "Choose a consequential but sandboxable task and first implement a deterministic workflow. Add one agent only for ambiguous decisions, then justify any specialist agents through context or permission isolation. Define typed state, events, task envelopes, tool schemas, terminal states, global budgets, and owners. Use MCP for composable capabilities without treating discovered servers as trusted. Draw every identity, data, and side-effect boundary before executing."),
        ("51.2 Durability and multi-agent coordination", "Checkpoint before and after effects, issue stable idempotency keys, retain receipts, propagate cancellation, and resume after injected crashes. Human approval binds to an immutable proposed action and expires. A supervisor may route only registered roles; specialists receive least context and tools; parallel results merge deterministically with dissent preserved. Shared state is authoritative only through validated transitions, not agent-authored prose."),
        ("51.3 Evaluation and adversarial testing", "Create a deterministic environment and frozen tasks. Compare deterministic, single-agent, and multi-agent variants under equal model, permission, token, tool-call, and time budgets. Score task success, tool choice and arguments, effects, duplicated work, conflicts, intervention, steps, tokens, latency, and critical violations. Inject malformed calls, poisoned MCP resources, revoked permissions, duplicate delivery, worker loss, stale approval, sandbox attacks, and malicious specialists."),
        ("51.4 Deployment and governance", "Serve the pinned model through vLLM or the selected engine behind authenticated ingress and admission control. Trace state transitions and effects without retaining sensitive payloads unnecessarily. Canary with read-only scopes, rehearse rollback, and publish a system card containing versions, architecture, threat model, evaluations, known limitations, monitoring, ownership, and incident response. Conclude with an ablation-based answer to whether multiple agents improved the workflow enough to remain."),
    ], [
        'architecture={"host":"policy + durable state","servers":["catalog","sandbox"],"agents":["supervisor","researcher","reviewer"],"human_gate":"external writes"}; print(architecture)',
        'states=["ready","planning","running","waiting_approval","committing","done","failed","cancelled"]; print(states)',
        'faults=["crash_before_effect","crash_after_effect","malicious_resource","revoked_scope","worker_timeout","duplicate_message"]; print(faults)',
        'comparison={"deterministic":.62,"single_agent":.81,"multi_agent":.84,"multi_agent_cost_ratio":2.3}; print(comparison,"keep only if bounded gains justify cost")'
    ], ["Implement crash and resume tests.", "Run matched-budget architecture ablations.", "Publish a system card and incident drill."])
